from common import File

wallpapers = {
    'macOS': [
        File(name='macOS_10.0_Cheetah_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-0_10.1.png'),
        File(name='macOS_10.0_Cheetah_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-0_10-1-6k.jpg'),  # 10.1 Puma shares the same wallpaper
        File(name='macOS_10.2_Jaguar_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-2.png'),
        File(name='macOS_10.2_Jaguar_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-2-6k.jpg'),
        File(name='macOS_10.3_Panther_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-3.png'),
        File(name='macOS_10.3_Panther_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-3-6k.jpg'),
        File(name='macOS_10.4_Tiger_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-4.png'),
        File(name='macOS_10.4_Tiger_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-4-6k.jpg'),
        File(name='macOS_10.5_Leopard_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-5.png'),
        File(name='macOS_10.5_Leopard_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-5-6k.jpg'),
        File(name='macOS_10.5_Leopard_Server_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-5-Server.jpg'),
        File(name='macOS_10.5_Leopard_Server_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-5-Server-6k.jpg'),
        File(name='macOS_10.6_Snow_Leopard_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-6.png'),
        File(name='macOS_10.6_Snow_Leopard_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-6-6k.jpg'),
        File(name='macOS_10.6_Snow_Leopard_Server_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-6-Server.jpg'),
        File(name='macOS_10.6_Snow_Leopard_Server_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-6-Server-6k.jpg'),
        File(name='macOS_10.7_Lion_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-7.png'),
        File(name='macOS_10.7_Lion_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-7-6k.jpg'),
        File(name='macOS_10.8_Mountain Lion_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-8.jpg'),
        File(name='macOS_10.8_Mountain Lion_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-8-6k.jpg'),
        File(name='macOS_10.9_Mavericks_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-9.jpg'),
        File(name='macOS_10.9_Mavericks_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-9-6k.jpg'),
        File(name='macOS_10.10_Yosemite_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-10.jpg'),
        File(name='macOS_10.10_Yosemite_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-10-6k.jpg'),
        File(name='macOS_10.11_El_Capitan_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-11.jpg'),
        File(name='macOS_10.11_El_Capitan_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-11-6k.jpg'),
        File(name='macOS_10.12_Sierra_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-12.jpg'),
        File(name='macOS_10.12_Sierra_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-12-6k.jpg'),
        File(name='macOS_10.13_High_Sierra_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-13.jpg'),
        File(name='macOS_10.13_High_Sierra_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-13-6k.jpg'),
        File(name='macOS_10.14_Mojave_Day_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-14-Day.jpg'),
        File(name='macOS_10.14_Mojave_Day_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-14-Day-6k.jpg'),
        File(name='macOS_10.14_Mojave_Night_default_5K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-14-Night.jpg'),
        File(name='macOS_10.14_Mojave_Night_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/10-14-Night-6k.jpg'),
        File(name='macOS_10.15_Catalina_Day_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-15-Day.jpg'),
        File(name='macOS_10.15_Catalina_Night_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/10-15-Night.jpg'),
        File(name='macOS_Big_Sur_Colorful_Day_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/11-0-Color-Day.jpg'),
        File(name='macOS_Big_Sur_Colorful_Night_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/11-0-Big-Sur-Color-Night.jpg'),
        File(name='macOS_Big_Sur_Day_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/11-0-Day.jpg'),
        File(name='macOS_Big_Sur_Night_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers/11-0-Night.jpg'),
        File(name='macOS_Monteray_Day_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/12-Light.jpg'),
        File(name='macOS_Monteray_Night_default_6K.jpg', url='https://512pixels.net/downloads/macos-wallpapers-6k/12-Dark.jpg'),
    ],
}
